# Generated by Django 3.2.2 on 2021-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
